spring.application.name=Formula1Api

# banco H2 em memoria, some quando a aplicacao para (usuario sa, senha vazia)
spring.datasource.url=jdbc:h2:mem:formula1db
spring.datasource.username=sa
spring.datasource.password=

# console do banco em http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# troca pra true se quiser ver os SQLs no console
spring.jpa.show-sql=false

# ordena os endpoints do swagger pelo metodo http
springdoc.swagger-ui.operations-sorter=method
